export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT = "LOGOUT";

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const UPDATE_INSTITUTE = "UPDATE_INSTITUTE";
export const UPDATE_SEMESTER_GROUP = "UPDATE_SEMESTER_GROUP";
export const UPDATE_SEMESTER_NUMBER = "UPDATE_SEMESTER_NUMBER";
export const UPDATE_DEGREE = "UPDATE_DEGREE";
export const UPDATE_ACADEMIC_YEAR = "UPDATE_ACADEMIC_YEAR";
export const DELETE_CURRENT = "DELETE_CURRENT";

export const AY_LOADED = "AY_LOADED";
export const AY_ERROR = "AY_ERROR";
export const INSTITUTES_LOADED = "INSTITUTES_LOADED";
export const INSTITUTES_ERROR = "INSTITUTES_ERROR";

export const EXAM_SCHEDULE_LOADED = "EXAM_SCHEDULE_LOADED";
export const EXAM_SCHEDULES_LOADED = "EXAM_SCHEDULES_LOADED";
export const EXAM_SCHEDULE_ERROR = "EXAM_SCHEDULE_ERROR";

export const PEDAGOGY_LOADED = "PEDAGOGY_LOADED";
export const PEDAGOGY_ERROR = "PEDAGOGY_ERROR";
export const PEDAGOGIES_LOADED = "PEDAGOGIES_LOADED";

export const NOT_ELIGIBLITY_LIST_LOADED = "NOT_ELIGIBLITY_LIST_LOADED";
export const NOT_ELIGIBLITY_LISTS_LOADED = "NOT_ELIGIBLITY_LISTS_LOADED";
export const NOT_ELIGIBLITY_LIST_ERROR = "NOT_ELIGIBLITY_LIST_ERROR";

// Admin
export const ADMIN_LOGIN = "ADMIN_LOGIN";
export const ADMIN_AUTH_ERROR = "ADMIN_AUTH_ERROR";
export const ADMIN_LOADED = "ADMIN_LOADED";
export const ADMIN_LOGOUT = "ADMIN_LOGOUT";

// Subjects
export const SUBJECTS_LOADED = "SUBJECTS_LOADED";
export const SUBJECTS_ERROR = "SUBJECTS_ERROR";

// Users
export const USERS_LOADED = "USERS_LOADED";
export const USERS_ERROR = "USERS_ERROR";

// Resources
export const RESOURCES_LOADED = "RESOURCES_LOADED";
export const RESOURCES_ERROR = "RESOURCES_ERROR";
